Profile/urls.py
from django.urls import path
from . import views as user_views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', user_views.user_login, name = 'login'),
    path('register/', user_views.register, name = 'register'),
    path('dashboard/', user_views.user_dashboard, name = 'dashboard'),
    path('logout/', user_views.user_loguot),
    path('profile/', user_views.profile, name = 'profile'),
    # path('stripe_payments/', user_views.stripe_payments, name='stripe_payments'),
    path('payments/', user_views.payments, name = 'payments'),
    path('roomate/', user_views.user_roomate_selection, name='user_roomate_selection'),
    path('alltransaction/', user_views.all_user_transaction, name='all_user_transaction'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hostel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('management/', include('landloard.urls')),
    path('hostels/', include('tenants.urls')),
    path('user/', include('Profile.urls')),
    path('', include('system.urls')),
    path('api/payments/', include('mpesa.api.urls')),
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from landloard.models import LandlordProfile, HostelPlan

# Create your models here.

class PaymentRequestHeaders(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(LandlordProfile, on_delete=models.CASCADE)
    merchant_request_id = models.CharField(max_length = 100)
    checkout_request_id = models.CharField(max_length = 100)
    response_description = models.CharField(max_length = 100)
    phone_number_used_for_payment = models.CharField(max_length = 100, blank=True)
    timestamp = models.DateTimeField(auto_now = True)


    def __str__(self):
        return  f'{self.hostel_name} request was {self.response_description}: checkout id = {self.checkout_request_id}' 


class TenantProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    your_full_name = models.CharField(max_length = 191, blank=True, null=True)
    phone_number = models.CharField(max_length = 191, blank=True, null=True)
    user_picture = models.ImageField(upload_to='tenant_profile')
    timestamp = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f'{self.your_full_name} : {self.phone_number} Profile'

class RoomateSelection(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    user_roomate = models.CharField(max_length=191)
    is_accepted = models.CharField(max_length=2, null=True, blank=True)

class HostelPaymentplan(models.Model):
    """Model definition for HostelPaymentplan. """

    # TODO: Define fields here
    tenant = models.ForeignKey(User, on_delete = models.CASCADE)
    paymentplan = models.ForeignKey(HostelPlan, on_delete=models.CASCADE)
    amountpaid = models.CharField(max_length=191)

    def __str__(self):
        """Unicode representation of HostelPaymentplan."""
        return f'{self.tenant} Payment Plan Is {self.amountpaid}'


class UserHostelPlan(models.Model):
    """Model definition for UserHostelPlan."""

    # TODO: Define fields here
    tenant = models.ForeignKey(User, on_delete = models.CASCADE)
    plan = models.ForeignKey(HostelPlan, on_delete=models.CASCADE)

    def __str__(self):
        """Unicode representation of UserHostelPlan."""
        return f'{self.plan} : {self.tenant} Plan'
    

Profile/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from . forms import RoomateSelectionForm, UserRegisterForm, UserLoginForm, PaymentForm, TenantProfileForm, UserHostelPlanForm, HostelPaymentplanForm
from . import lipanampesa
from urllib3.exceptions import ProtocolError, ConnectionError
# m-pesa
import requests
import json
from .access_token import generate_access_token
from .utils import timestamp_convertion
from . import keys
from requests.auth import HTTPBasicAuth
from .encode_base64 import generate_password
#
from . models import PaymentRequestHeaders, TenantProfile, UserHostelPlan, HostelPaymentplan, RoomateSelection
from mpesa.models import LNMOnline
from landloard.models import HostelPlan


#
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Account created for {username}! Now Login')
            form.save()
            return redirect('/user/')  # will change to dashboard
    else:
        form = UserRegisterForm()
    return render(request, 'student_profile/register.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        messages.success(
            request, f'login was Success!{ request.user.username}')
        return redirect('/user/dashboard/')
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            login(request, user)

            messages.success(request, f'login was Success {username} !!!')
            return redirect('/user/dashboard/')
        else:
            messages.success(
                request, f'login Error !!!! Provide Correct Username And Password')
    else:
        form = UserLoginForm()
    return render(request, 'student_profile/login.html', {'form': form})


@login_required(login_url='/user/')
def user_dashboard(request):
    context = {}
    # if request.user.is_authenticated:

    return render(request, 'student_profile/studentpages/dashboard.html', context)


@login_required(login_url='/user/')
def profile(request):
    context = {}
    if request.user.is_authenticated:
        user_qs = TenantProfile.objects.filter(user_id=request.user.id)
        context = {}
        if request.method == 'POST':
            form = TenantProfileForm(request.POST, request.FILES)
            context['form'] = form
            if form.is_valid():
                your_full_name = form.cleaned_data.get('your_full_name')

                user_qs = TenantProfile.objects.filter(user_id=request.user.id)
                context['user_qs'] = user_qs
                if user_qs.count() == 1:
                    user = user_qs.first()
                    if user:
                        messages.success(
                            request, f'You Already Have A Profile {your_full_name} !')
                        return redirect('/user/profile/')
                else:
                    messages.success(
                        request, f'Account Profile for {your_full_name} is Created !')
                    obj = form.save(commit=False)
                    obj.user_id = request.user.id
                    obj.save()
                    return redirect('/user/profile/')
            else:
                messages.success(request, f'Fill All Required fields !!')
        else:
            form = TenantProfileForm()
            context['form'] = form
            context['user_qs'] = user_qs

    return render(request, 'student_profile/studentpages/profile.html', context)


@login_required(login_url='/user/')
def all_user_transaction(request):
    context = {}
    if request.user.is_authenticated:
        previous_transaction = PaymentRequestHeaders.objects.filter(
            user=request.user.id)
        lnmponline = LNMOnline.objects.all()
        context['lnmponline'] = lnmponline
        context['previous_transaction'] = previous_transaction

    return render(request, 'student_profile/studentpages/transaction.html', context)


@login_required(login_url='/user')
def user_roomate_selection(request):
    context = {}
    if request.user.is_authenticated:
        hostel_payment_plan = HostelPaymentplan.objects.all()
        hostel_payment_plan_qs = HostelPaymentplan.objects.filter(tenant_id = request.user.id).first()
        user_hostel_plan = UserHostelPlan.objects.filter(tenant_id = request.user.id)
        roomate_qs = RoomateSelection.objects.filter(user_id = request.user.id)
        context['hostel_payment_plan'] = hostel_payment_plan
        context['hostel_payment_plan_qs'] = hostel_payment_plan_qs
        context['user_hostel_plan'] = user_hostel_plan
        context['roomate_qs'] = roomate_qs
        if request.method == 'POST':
            roomate_selecton_save = RoomateSelection.objects.create(
                user_id = request.POST['user_id'],
                user_roomate = request.POST['user_roomate'],
                is_accepted = request.POST['is_accepted'],
            )
            roomate_selecton_save.save()
            return redirect('/user/roomate/')
        else:
            form = RoomateSelectionForm()
            context['form'] = form
        return render(request, 'student_profile/studentpages/roomate.html', context)


@login_required(login_url='/user/')
def payments(request):
    context = {}

    if request.user.is_authenticated:
        hostelplan = HostelPlan.objects.all()
        previous_transaction = PaymentRequestHeaders.objects.filter(
            user=request.user.id)
        hostel_plan_check_qs = UserHostelPlan.objects.filter(
            tenant=request.user.id)  # tenant->user request.user.landlordprofile.id
        hostel_payment_plan_check_qs = HostelPaymentplan.objects.filter(
            tenant=request.user.id)
        # hostel_plan_check_qs = UserHostelPlan.objects.all()
        context['hostel_plan_check_qs'] = hostel_plan_check_qs
        context['previous_transaction'] = previous_transaction
        context['hostelplan'] = hostelplan
        context['hostel_payment_plan_check_qs'] = hostel_payment_plan_check_qs
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        plan_form = UserHostelPlanForm(request.POST)
        hostel_payment_plan_form = HostelPaymentplanForm(request.POST)
        context['form'] = form
        context['plan_form'] = plan_form
        context['hostel_payment_plan_form'] = hostel_payment_plan_form
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            user_id = form.cleaned_data.get('user_id')
            # time formatting
            formarted_time = timestamp_convertion()
            # to be implemented on production scale
            business_short_code = request.POST['business_short_code']

            hostel_name = request.POST['hostel_name_id']
            amount_payable = request.POST['amount']

            # base64 encode
            decoded_password = generate_password(formarted_time)
            access_token = generate_access_token()
            api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
            headers = {"Authorization": "Bearer %s" % access_token}
            request = {
                "BusinessShortCode": keys.business_short_code,
                "Password": decoded_password,
                "Timestamp": formarted_time,
                "TransactionType": "CustomerBuyGoodsOnline",  # CustomerPayBillOnline
                "Amount": amount_payable,
                "PartyA": phone_number,
                "PartyB": keys.business_short_code,
                "PhoneNumber": phone_number,
                "CallBackURL": "https://accomodations.herokuapp.com/api/payments/lnm/",
                "AccountReference": "Test004Clinton",
                "TransactionDesc": "Rent pay"
            }

            response = requests.post(api_url, json=request, headers=headers)

            mystr = response.text
            obbstr = json.loads(mystr)
            merchant_request_id = obbstr['MerchantRequestID']
            checkout_request_id = obbstr['CheckoutRequestID']
            response_description = obbstr['ResponseDescription']

            payment_request_headers = PaymentRequestHeaders.objects.create(
                merchant_request_id=merchant_request_id,
                checkout_request_id=checkout_request_id,
                response_description=response_description,
                user_id=user_id,
                hostel_name_id=hostel_name,
                phone_number_used_for_payment=phone_number,
            )

            context['checkout_request_id'] = checkout_request_id
            context['response_description'] = response_description
            payment_request_headers.save()

            return redirect('/user/payments/')
        elif plan_form.is_valid():
            messages.success(
                request, f"{plan_form.cleaned_data.get('plan')} Selected Successfully")
            obj = plan_form.save(commit=False)
            obj.tenant_id = request.user.id
            obj.save()
            return redirect('/user/payments/')
        elif hostel_payment_plan_form.is_valid():
            messages.success(
                request, f"{request.POST['amountpaid']} Selected Successfully")
            obj = hostel_payment_plan_form.save(commit=False)
            obj.tenant_id = request.user.id
            obj.paymentplan_id = hostel_name = request.POST['paymentplan_id']
            obj.amountpaid = hostel_name = request.POST['amountpaid']
            obj.save()
    else:

Profile/templates/student_profile/studentpages/dashboard.html
{% extends 'student_profile/base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %} 
{% include "student_profile/partials/authNav.html" %} 
<div class="row">
  <div class="col-md-12 m-1 card">
    <h4 class="card-title p-2">Previous Payments:</h4>
      <p class="card-description p-2">
        {{ user.username }} 
        <code>Here Are The Previous Payments Request:</code>
      </p>
  </div>
</div>
{% include "student_profile/partials/authFooter.html" %} {% endblock %}

Profile/templates/student_profile/studentpages/pay.html
{% extends 'student_profile/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block scripts %}


{% endblock %}
{% block content %}

{% include "student_profile/partials/authNav.html" %}
<div class="row">
  <div class="col-md-6 m-1 card">
    {% if messages %}
    {% for  message in messages %}
    <div class="alert alert-{{message.tags}}">
      {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% if hostel_plan_check_qs.count == 0 %}
    <p class="p-4">Select Hostel</p>
    <form action="." method="POST" class="p-5">
      {% csrf_token %}
      <input type="text" name="tenant_id" hidden="true" value="{{ user.id }}" id="id_tenant" required>
      {{ plan_form|crispy }}
      <div class="form-group">
        <button type="submit" class="btn btn-info mt-3 submit-btn">
          Select Hostel
        </button>
      </div>
    </form>
    {% else %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Hostel Name</th>
          <th>Your UserName</th>
          <th class="text-danger">Amount To Pay</th>
        </tr>
      </thead>
      <tbody>
        {% for hostel_plan_check in hostel_plan_check_qs %}
        <tr>
          <td>{{ hostel_plan_check.plan }}</td>
          <td>{{ hostel_plan_check.tenant }}</td>
          <td class="text-danger">

            {% for hosteluserplan in hostel_payment_plan_check_qs %}
            {{hosteluserplan.amountpaid}}
            {% endfor %}

          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


    {% if hostel_plan_check_qs.count >= 1 %}
    <form action="." method="POST" class="p-5" {% if hostel_payment_plan_check_qs.count >= 1 %} style="display: none;"
      {% endif %}>
      {% csrf_token %}
      {% for hostelshortcode in hostelplan %}

      {% for hostel_plan_check in hostel_plan_check_qs %}

      {% if hostel_plan_check.plan_id == hostelshortcode.id %}
      <input type="text" hidden="true" name="paymentplan_id" value="{{hostelshortcode.id}}" id="id_paymentplan"
        required>
      <input type="text" hidden="true" name="tenant_id" value="{{user.id}}" id="id_tenant" required>
      <div class="form-group">
        <label for="hostel-Plan">Select Hostel Plan You Will Pay</label>
        <table class="table table-bordered table-responsive">
          <thead>
            <tr>
              <th>Single Room Price</th>
              <th>Double Room Price</th>
              <th>Self Contained Price</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <div class="custom-control custom-radio custom-control-inline">
                  <input type="radio" id="customRadioInline1" name="amountpaid"
                    value="{{hostelshortcode.single_room_payment_price}}" class="custom-control-input">
                  <label class="custom-control-label"
                    for="customRadioInline1">{{hostelshortcode.single_room_payment_price}}</label>
                </div>
              </td>
              <td>
                <div class="custom-control custom-radio custom-control-inline">
                  <input type="radio" id="customRadioInline2" name="amountpaid"
                    value="{{hostelshortcode.double_room_payment_price}}" class="custom-control-input">
                  <label class="custom-control-label"
                    for="customRadioInline2">{{hostelshortcode.double_room_payment_price}}</label>
                </div>
              </td>
              <td>
                <div class="custom-control custom-radio custom-control-inline">
                  <input type="radio" id="customRadioInline3" name="amountpaid"
                    value="{{hostelshortcode.self_contained_payment_price}}" class="custom-control-input">
                  <label class="custom-control-label"
                    for="customRadioInline3">{{hostelshortcode.self_contained_payment_price}}</label>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {% endif %}
      {% endfor %}
      {% endfor %}
      <button type="submit" class="btn btn-info mt-3 submit-btn">
        Submit Plan
      </button>
    </form>
    {% endif %}

    {% endif %}
  </div>

  <div class="col-md-5 m-1 card p-3">
    {% if hostel_plan_check_qs.count >= 1 %}
    <h3>Make M-Pesa Payments</h3>
    <p class="text-danger">Phone Number Must Be Written In This Format.(254723465789)</p>
    <form action="" method="POST" enctype="multipart/form-data" {% if hostel_payment_plan_check_qs.count == 0 %}
      style="display: none;" {% endif %}>
      {% csrf_token %}
      <div class="form-group">
        <label for="phone_number">Phone Number eg 254712******</label>
        {{ form.phone_number }}
      </div>
      {{ form.test }}
      <input type="text" name="user_id" hidden="true" value="{{ user.id }}" id="id_number" required>

      {% for hostelshortcode in hostelplan %}

        {% for hostel_plan_check in hostel_plan_check_qs %}

          {% if hostel_plan_check.plan_id == hostelshortcode.id %}
            <div class="form-group">
              <label for="Pay Bill">Pay Bill</label>
              <select name="business_short_code" class="form-control" required id="id_business_short_code">
                <option>---Select Hostel Pay Bill Or Till Number---</option>
                <option value="{{hostelshortcode.mpesa_shotcode}}">
                  {{hostelshortcode.hostel_name}}: Pay Bill Or Till Number:
                  {{hostelshortcode.mpesa_shotcode}}
                </option>
              </select>
            </div>
            <input type="text" name="hostel_name_id" hidden="true" value="{{hostelshortcode.id}}" id="id_hostel_name"
              required>
            <div class="form-group">
              <label for="hostel-Plan">Select Hostel Plan You Will Pay</label>
              <table class="table table-bordered table-responsive">
                <thead>
                  <tr>
                    <th>Single Room Price</th>
                    <th>Double Room Price</th>
                    <th>Self Contained Price</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadio1" name="amount"
                          value="{{hostelshortcode.single_room_payment_price}}" class="custom-control-input">
                        <label class="custom-control-label"
                          for="customRadio1">{{hostelshortcode.single_room_payment_price}}</label>
                      </div>
                    </td>
                    <td>
                      <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadio2" name="amount"
                          value="{{hostelshortcode.double_room_payment_price}}" class="custom-control-input">
                        <label class="custom-control-label"
                          for="customRadio2">{{hostelshortcode.double_room_payment_price}}</label>
                      </div>
                    </td>
                    <td>
                      <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadio3" name="amount"
                          value="{{hostelshortcode.self_contained_payment_price}}" class="custom-control-input">
                        <label class="custom-control-label"
                          for="customRadio3">{{hostelshortcode.self_contained_payment_price}}</label>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          {% endif %}
        {% endfor %}
      {% endfor %}

      <div class="form-group">
        <button type="submit" class="btn btn-info mt-3 submit-btn">
          Pay
        </button>
      </div>
    </form>
    {% else %}
    <h3>Make M-Pesa Payments</h3>
    <p class="text-danger">Select Hostel First In Order To Make Payments</p>
    {% endif %}
  </div>

</div>
<div class="row">
  <div class="col-md-11 m-1 card">
    <h4 class="card-title p-2">Previous M-Pesa Transaction:</h4>
    <p class="card-description p-2">
      {{ user.username }}
      <code>Here Are The Previous Success Transaction Request:</code>
    </p>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                Time
              </th>
              <th>
                Phone Number Used For Payments
              </th>
              <th>
                Description
              </th>
            </tr>
          </thead>
          <tbody>
            {% for transaction in previous_transaction %}
            <tr>
              <td class="py-1">
                {{ transaction.timestamp }}
              </td>
              <td>
                {{ transaction.phone_number_used_for_payment }}
              </td>
              <td>
                {{ transaction.response_description }}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
{% include "student_profile/partials/authFooter.html" %} {% endblock %}

Profile/templates/student_profile/studentpages/profile.html
{% extends 'student_profile/base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %} 
{% include "student_profile/partials/authNav.html" %} 
<div class="row">
  <div class="col-md-7 m-1 card">
    <h4 class="card-title p-2">Previous Payments:</h4>
      <p class="card-description p-2">
        {{ user.username }} 
        <code>Profile</code>
      </p>
      <div class="row">
          <div class="col-md-2">
              <div class="card text-center">
                 <p>
                    <img src="/user{{ user.tenantprofile.user_picture.url }}" style="height: 50%; width: 50%; border-radius: 50%;" alt="">
                 </p> 
              </div>
          </div>
          <div class="col-md-10">
              <div class="card">
                  <table class="table table-striped">
                      <thead>
                          <tr>
                              <th data-field="id">Full Name</th>
                              <th data-field="name">Username</th>
                              <th data-field="price">Email</th>
                              <th data-field="price">Phone Number</th>
                          </tr>
                      </thead>
                      <tbody>
                          <tr>
                              <td>{{ user.tenantprofile.your_full_name }}</td>
                              <td>{{user.username}}</td>
                              <td>{{user.email}}</td>
                              <td>{{user.tenantprofile.phone_number}}</td>
                          </tr>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>
  <div class="col-md-4 m-1 card">
    {% if messages %}
        {% for  message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    <h4 class="card-title p-2">{{ user.username }}: Make Your Profile:</h4>
        <div class="card-body">
            <form action="." method="POST" enctype="multipart/form-data">
            
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>
</div>
{% include "student_profile/partials/authFooter.html" %} {% endblock %}

Profile/templates/student_profile/studentpages/roomate.html
{% extends 'student_profile/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block scripts %}


{% endblock %}
{% block content %}

{% include "student_profile/partials/authNav.html" %}

<div class="row">
    <div class="col-md-5 m-1 card">
        <div class="card-body">
            <h4 class="text-info mb-2">Roomate Requests</h4>
            <table class="table table-responsive table-striped">
                <thead>
                    <tr>
                        <th data-field="id">Username</th>
                        <th data-field="name">Roomate Name</th>
                        <th>Confirmed</th>
                        <th colspan="2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for roomate in roomate_qs %}
                        <tr>
                            <td>{{roomate.user}}</td>
                            <td>{{roomate.user_roomate}}</td>
                            <td>{{roomate.is_accepted}}</td>
                            <td class="text-success">
                                <button type="submit" class="btn btn-success">Accept</button>
                            </td>
                            <td class="text-danger">
                                <button type="submit" class="btn btn-danger">Reject</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-body">
            <h3 class="text-info text-center">
                {{ user.tenantprofile.your_full_name }} | 
                Your Roomate Is Blabla
            </h3>
        </div>
        <div class="card-body">     
            <h4>People With Same Payment Plan As Me</h4>       
            <table class="table table-striped table-responsive">
                <thead>
                    <tr>
                        <th data-field="id">Username</th>
                        <th data-field="name">Hostel</th>
                        <th data-field="price">Amount To Pay</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_payment in hostel_payment_plan %}
                        {% for user_hostel in user_hostel_plan %}
                        
                            {% if user_payment.paymentplan == user_hostel.plan %}
                                
                                {% if user_payment.amountpaid == hostel_payment_plan_qs.amountpaid %}
                                    <tr>
                                        <td>{{ user_payment.tenant }}</td>
                                        <td>{{ user_payment.paymentplan }}</td>
                                        <td> {{ user_payment.amountpaid }}</td>
                                    </tr> 
                                {% endif %}
                                    
                            
                            {% endif %}
                            
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table> 
        </div>
    </div>
    <div class="col-md-6 m-1 card">
        <div class="card-body">
            <h4 class="text-info">Request For Roomate</h4>
        </div>
        <div class="card-body">
            {% if roomate_qs.count == 1 %}
            <h1>Wait For Response</h1>
            {% else %}   
                <form action="." method="POST">
                    {% csrf_token %} 
                    <input type="text" hidden class="form-control" name="user_id" value="{{user.id}}">              
                    <div class="form-group">
                        <label for="">Select Roommate</label>
                    <select name="user_roomate" class="select form-control" required id="id_user"> 
                            <option value="" selected>----Select Roommate----</option> 
                            {% for user_payment in hostel_payment_plan %}
                                {% for user_hostel in user_hostel_plan %}
                                    {% if user_payment.paymentplan == user_hostel.plan %}
                                        {% if user_payment.amountpaid == hostel_payment_plan_qs.amountpaid %}
                                            <option value="{{ user_payment.tenant }}">{{ user_payment.tenant }} : {{ user_payment.paymentplan }}</option>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </select> 
                    </div>
                    <input type="text" hidden class="form-control" name="is_accepted" value="0"> 
                    <button type="submit" class="btn btn-info">Request</button>
                </form>
            {% endif %}
        </div>
    </div>
</div>


{% include "student_profile/partials/authFooter.html" %}

{% endblock %}